#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/


/* Definitions for peripheral SYS_MB */
#define XPAR_SYS_MB_ADDR_SIZE 32
#define XPAR_SYS_MB_ADDR_TAG_BITS 16
#define XPAR_SYS_MB_ALLOW_DCACHE_WR 1
#define XPAR_SYS_MB_ALLOW_ICACHE_WR 1
#define XPAR_SYS_MB_AREA_OPTIMIZED 0
#define XPAR_SYS_MB_ASYNC_INTERRUPT 1
#define XPAR_SYS_MB_ASYNC_WAKEUP 3
#define XPAR_SYS_MB_AVOID_PRIMITIVES 0
#define XPAR_SYS_MB_BASE_VECTORS 0x0000000000000000
#define XPAR_SYS_MB_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_SYS_MB_CACHE_BYTE_SIZE 16384
#define XPAR_SYS_MB_DADDR_SIZE 32
#define XPAR_SYS_MB_DATA_SIZE 32
#define XPAR_SYS_MB_DCACHE_ADDR_TAG 16
#define XPAR_SYS_MB_DCACHE_ALWAYS_USED 1
#define XPAR_SYS_MB_DCACHE_BASEADDR 0x80000000
#define XPAR_SYS_MB_DCACHE_BYTE_SIZE 16384
#define XPAR_SYS_MB_DCACHE_DATA_WIDTH 0
#define XPAR_SYS_MB_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_SYS_MB_DCACHE_HIGHADDR 0xBFFFFFFF
#define XPAR_SYS_MB_DCACHE_LINE_LEN 4
#define XPAR_SYS_MB_DCACHE_USE_WRITEBACK 0
#define XPAR_SYS_MB_DCACHE_VICTIMS 8
#define XPAR_SYS_MB_DC_AXI_MON 0
#define XPAR_SYS_MB_DEBUG_COUNTER_WIDTH 32
#define XPAR_SYS_MB_DEBUG_ENABLED 1
#define XPAR_SYS_MB_DEBUG_EVENT_COUNTERS 5
#define XPAR_SYS_MB_DEBUG_EXTERNAL_TRACE 0
#define XPAR_SYS_MB_DEBUG_INTERFACE 0
#define XPAR_SYS_MB_DEBUG_LATENCY_COUNTERS 1
#define XPAR_SYS_MB_DEBUG_PROFILE_SIZE 0
#define XPAR_SYS_MB_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_SYS_MB_DEBUG_TRACE_SIZE 8192
#define XPAR_SYS_MB_DIV_ZERO_EXCEPTION 1
#define XPAR_SYS_MB_DP_AXI_MON 0
#define XPAR_SYS_MB_DYNAMIC_BUS_SIZING 0
#define XPAR_SYS_MB_D_AXI 1
#define XPAR_SYS_MB_D_LMB 1
#define XPAR_SYS_MB_D_LMB_MON 0
#define XPAR_SYS_MB_ECC_USE_CE_EXCEPTION 0
#define XPAR_SYS_MB_EDGE_IS_POSITIVE 1
#define XPAR_SYS_MB_ENABLE_DISCRETE_PORTS 0
#define XPAR_SYS_MB_ENDIANNESS 1
#define XPAR_SYS_MB_FAULT_TOLERANT 0
#define XPAR_SYS_MB_FPU_EXCEPTION 0
#define XPAR_SYS_MB_FREQ 100000000
#define XPAR_SYS_MB_FSL_EXCEPTION 0
#define XPAR_SYS_MB_FSL_LINKS 0
#define XPAR_SYS_MB_IADDR_SIZE 32
#define XPAR_SYS_MB_ICACHE_ALWAYS_USED 1
#define XPAR_SYS_MB_ICACHE_BASEADDR 0x80000000
#define XPAR_SYS_MB_ICACHE_DATA_WIDTH 0
#define XPAR_SYS_MB_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_SYS_MB_ICACHE_HIGHADDR 0xBFFFFFFF
#define XPAR_SYS_MB_ICACHE_LINE_LEN 8
#define XPAR_SYS_MB_ICACHE_STREAMS 1
#define XPAR_SYS_MB_ICACHE_VICTIMS 8
#define XPAR_SYS_MB_IC_AXI_MON 0
#define XPAR_SYS_MB_ILL_OPCODE_EXCEPTION 1
#define XPAR_SYS_MB_IMPRECISE_EXCEPTIONS 0
#define XPAR_SYS_MB_INSTR_SIZE 32
#define XPAR_SYS_MB_INTERCONNECT 2
#define XPAR_SYS_MB_INTERRUPT_IS_EDGE 0
#define XPAR_SYS_MB_INTERRUPT_MON 0
#define XPAR_SYS_MB_IP_AXI_MON 0
#define XPAR_SYS_MB_I_AXI 0
#define XPAR_SYS_MB_I_LMB 1
#define XPAR_SYS_MB_I_LMB_MON 0
#define XPAR_SYS_MB_LMB_DATA_SIZE 32
#define XPAR_SYS_MB_LOCKSTEP_MASTER 0
#define XPAR_SYS_MB_LOCKSTEP_SELECT 0
#define XPAR_SYS_MB_LOCKSTEP_SLAVE 0
#define XPAR_SYS_MB_M0_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M0_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M1_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M1_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M2_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M2_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M3_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M3_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M4_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M4_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M5_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M5_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M6_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M6_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M7_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M7_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M8_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M8_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M9_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M9_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M10_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M10_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M11_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M11_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M12_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M12_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M13_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M13_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M14_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M14_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_M15_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_M15_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_MMU_DTLB_SIZE 4
#define XPAR_SYS_MB_MMU_ITLB_SIZE 2
#define XPAR_SYS_MB_MMU_PRIVILEGED_INSTR 0
#define XPAR_SYS_MB_MMU_TLB_ACCESS 3
#define XPAR_SYS_MB_MMU_ZONES 2
#define XPAR_SYS_MB_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_SYS_MB_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_SYS_MB_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_SYS_MB_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_SYS_MB_M_AXI_DC_DATA_WIDTH 32
#define XPAR_SYS_MB_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_SYS_MB_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_SYS_MB_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_SYS_MB_M_AXI_DC_USER_SIGNALS 0
#define XPAR_SYS_MB_M_AXI_DC_USER_VALUE 31
#define XPAR_SYS_MB_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_SYS_MB_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_SYS_MB_M_AXI_DP_DATA_WIDTH 32
#define XPAR_SYS_MB_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_SYS_MB_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_SYS_MB_M_AXI_D_BUS_EXCEPTION 1
#define XPAR_SYS_MB_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_SYS_MB_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_SYS_MB_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_SYS_MB_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_SYS_MB_M_AXI_IC_DATA_WIDTH 32
#define XPAR_SYS_MB_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_SYS_MB_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_SYS_MB_M_AXI_IC_USER_SIGNALS 0
#define XPAR_SYS_MB_M_AXI_IC_USER_VALUE 31
#define XPAR_SYS_MB_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_SYS_MB_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_SYS_MB_M_AXI_IP_DATA_WIDTH 32
#define XPAR_SYS_MB_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_SYS_MB_M_AXI_I_BUS_EXCEPTION 1
#define XPAR_SYS_MB_NUMBER_OF_PC_BRK 1
#define XPAR_SYS_MB_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_SYS_MB_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_SYS_MB_NUM_SYNC_FF_CLK 2
#define XPAR_SYS_MB_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_SYS_MB_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_SYS_MB_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_SYS_MB_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_SYS_MB_OPCODE_0X0_ILLEGAL 1
#define XPAR_SYS_MB_OPTIMIZATION 0
#define XPAR_SYS_MB_PC_WIDTH 32
#define XPAR_SYS_MB_PIADDR_SIZE 32
#define XPAR_SYS_MB_PVR 2
#define XPAR_SYS_MB_PVR_USER1 0x00
#define XPAR_SYS_MB_PVR_USER2 0x00000000
#define XPAR_SYS_MB_RESET_MSR 0x00000000
#define XPAR_SYS_MB_RESET_MSR_BIP 0
#define XPAR_SYS_MB_RESET_MSR_DCE 0
#define XPAR_SYS_MB_RESET_MSR_EE 0
#define XPAR_SYS_MB_RESET_MSR_EIP 0
#define XPAR_SYS_MB_RESET_MSR_ICE 0
#define XPAR_SYS_MB_RESET_MSR_IE 0
#define XPAR_SYS_MB_S0_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S0_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S1_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S1_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S2_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S2_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S3_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S3_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S4_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S4_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S5_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S5_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S6_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S6_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S7_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S7_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S8_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S8_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S9_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S9_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S10_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S10_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S11_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S11_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S12_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S12_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S13_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S13_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S14_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S14_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_S15_AXIS_DATA_WIDTH 32
#define XPAR_SYS_MB_S15_AXIS_PROTOCOL GENERIC
#define XPAR_SYS_MB_SCO 0
#define XPAR_SYS_MB_TRACE 0
#define XPAR_SYS_MB_UNALIGNED_EXCEPTIONS 1
#define XPAR_SYS_MB_USE_BARREL 1
#define XPAR_SYS_MB_USE_BRANCH_TARGET_CACHE 0
#define XPAR_SYS_MB_USE_CONFIG_RESET 0
#define XPAR_SYS_MB_USE_DCACHE 1
#define XPAR_SYS_MB_USE_DIV 1
#define XPAR_SYS_MB_USE_EXTENDED_FSL_INSTR 0
#define XPAR_SYS_MB_USE_EXT_BRK 0
#define XPAR_SYS_MB_USE_EXT_NM_BRK 0
#define XPAR_SYS_MB_USE_FPU 0
#define XPAR_SYS_MB_USE_HW_MUL 2
#define XPAR_SYS_MB_USE_ICACHE 1
#define XPAR_SYS_MB_USE_INTERRUPT 1
#define XPAR_SYS_MB_USE_MMU 3
#define XPAR_SYS_MB_USE_MSR_INSTR 1
#define XPAR_SYS_MB_USE_NON_SECURE 0
#define XPAR_SYS_MB_USE_PCMP_INSTR 1
#define XPAR_SYS_MB_USE_REORDER_INSTR 1
#define XPAR_SYS_MB_USE_STACK_PROTECTION 0
#define XPAR_SYS_MB_COMPONENT_NAME system_sys_mb_0
#define XPAR_SYS_MB_EDK_IPTYPE PROCESSOR
#define XPAR_SYS_MB_EDK_SPECIAL microblaze
#define XPAR_SYS_MB_G_TEMPLATE_LIST 4
#define XPAR_SYS_MB_G_USE_EXCEPTIONS 1

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_MICROBLAZE_ID 0
#define XPAR_MICROBLAZE_ADDR_SIZE 32
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 16
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 16384
#define XPAR_MICROBLAZE_DADDR_SIZE 32
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 16
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x80000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 16384
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0xBFFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 8
#define XPAR_MICROBLAZE_DC_AXI_MON 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 1
#define XPAR_MICROBLAZE_DP_AXI_MON 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_D_LMB_MON 0
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_IADDR_SIZE 32
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x80000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0xBFFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 8
#define XPAR_MICROBLAZE_ICACHE_STREAMS 1
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 8
#define XPAR_MICROBLAZE_IC_AXI_MON 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 1
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INSTR_SIZE 32
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_IP_AXI_MON 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_I_LMB_MON 0
#define XPAR_MICROBLAZE_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 2
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 1
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 1
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 1
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_PVR 2
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 1
#define XPAR_MICROBLAZE_USE_BARREL 1
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 1
#define XPAR_MICROBLAZE_USE_DIV 1
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 2
#define XPAR_MICROBLAZE_USE_ICACHE 1
#define XPAR_MICROBLAZE_USE_INTERRUPT 1
#define XPAR_MICROBLAZE_USE_MMU 3
#define XPAR_MICROBLAZE_USE_MSR_INSTR 1
#define XPAR_MICROBLAZE_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 1
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME system_sys_mb_0
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 4
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 1

/******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_MB
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 3U

/* Definitions for peripheral SYS_DLMB_CNTLR */
#define XPAR_SYS_DLMB_CNTLR_DEVICE_ID 0U
#define XPAR_SYS_DLMB_CNTLR_DATA_WIDTH 32U
#define XPAR_SYS_DLMB_CNTLR_ECC 0U
#define XPAR_SYS_DLMB_CNTLR_FAULT_INJECT 0U
#define XPAR_SYS_DLMB_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_SYS_DLMB_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_SYS_DLMB_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_SYS_DLMB_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_SYS_DLMB_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_SYS_DLMB_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_SYS_DLMB_CNTLR_WRITE_ACCESS 2U
#define XPAR_SYS_DLMB_CNTLR_BASEADDR 0x00000000U
#define XPAR_SYS_DLMB_CNTLR_HIGHADDR 0x0001FFFFU
#define XPAR_SYS_DLMB_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_SYS_DLMB_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral SYS_ILMB_CNTLR */
#define XPAR_SYS_ILMB_CNTLR_DEVICE_ID 1U
#define XPAR_SYS_ILMB_CNTLR_DATA_WIDTH 32U
#define XPAR_SYS_ILMB_CNTLR_ECC 0U
#define XPAR_SYS_ILMB_CNTLR_FAULT_INJECT 0U
#define XPAR_SYS_ILMB_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_SYS_ILMB_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_SYS_ILMB_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_SYS_ILMB_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_SYS_ILMB_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_SYS_ILMB_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_SYS_ILMB_CNTLR_WRITE_ACCESS 2U
#define XPAR_SYS_ILMB_CNTLR_BASEADDR 0x00000000U
#define XPAR_SYS_ILMB_CNTLR_HIGHADDR 0x0001FFFFU
#define XPAR_SYS_ILMB_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_SYS_ILMB_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral LMB_BRAM_IF_CNTLR_0 */
#define XPAR_LMB_BRAM_IF_CNTLR_0_DEVICE_ID 2U
#define XPAR_LMB_BRAM_IF_CNTLR_0_DATA_WIDTH 32U
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC 1U
#define XPAR_LMB_BRAM_IF_CNTLR_0_FAULT_INJECT 0U
#define XPAR_LMB_BRAM_IF_CNTLR_0_CE_FAILING_REGISTERS 0U
#define XPAR_LMB_BRAM_IF_CNTLR_0_UE_FAILING_REGISTERS 0U
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC_STATUS_REGISTERS 0U
#define XPAR_LMB_BRAM_IF_CNTLR_0_CE_COUNTER_WIDTH 0U
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC_ONOFF_REGISTER 0U
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_LMB_BRAM_IF_CNTLR_0_WRITE_ACCESS 2U
#define XPAR_LMB_BRAM_IF_CNTLR_0_S_AXI_CTRL_BASEADDR 0x76000000U
#define XPAR_LMB_BRAM_IF_CNTLR_0_S_AXI_CTRL_HIGHADDR 0x7601FFFFU


/******************************************************************/

/* Canonical definitions for peripheral SYS_DLMB_CNTLR */
#define XPAR_BRAM_0_DEVICE_ID XPAR_SYS_DLMB_CNTLR_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_0_WRITE_ACCESS 2U
#define XPAR_BRAM_0_BASEADDR 0x00000000U
#define XPAR_BRAM_0_HIGHADDR 0x0001FFFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral SYS_ILMB_CNTLR */
#define XPAR_BRAM_1_DEVICE_ID XPAR_SYS_ILMB_CNTLR_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32U
#define XPAR_BRAM_1_ECC 0U
#define XPAR_BRAM_1_FAULT_INJECT 0U
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_1_WRITE_ACCESS 2U
#define XPAR_BRAM_1_BASEADDR 0x00000000U
#define XPAR_BRAM_1_HIGHADDR 0x0001FFFFU
#define XPAR_BRAM_1_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_1_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral LMB_BRAM_IF_CNTLR_0 */
#define XPAR_BRAM_2_DEVICE_ID XPAR_LMB_BRAM_IF_CNTLR_0_DEVICE_ID
#define XPAR_BRAM_2_DATA_WIDTH 32U
#define XPAR_BRAM_2_ECC 1U
#define XPAR_BRAM_2_FAULT_INJECT 0U
#define XPAR_BRAM_2_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_2_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_2_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_2_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_2_WRITE_ACCESS 2U
#define XPAR_BRAM_2_CTRL_BASEADDR 0x76000000U
#define XPAR_BRAM_2_CTRL_HIGHADDR 0x7601FFFFU


/******************************************************************/

/* Definitions for driver EMACLITE */
#define XPAR_XEMACLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_ETHERNET */
#define XPAR_AXI_ETHERNET_DEVICE_ID 0
#define XPAR_AXI_ETHERNET_BASEADDR 0x40E00000
#define XPAR_AXI_ETHERNET_HIGHADDR 0x40E01FFF
#define XPAR_AXI_ETHERNET_TX_PING_PONG 1
#define XPAR_AXI_ETHERNET_RX_PING_PONG 1
#define XPAR_AXI_ETHERNET_INCLUDE_MDIO 1
#define XPAR_AXI_ETHERNET_INCLUDE_INTERNAL_LOOPBACK 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_ETHERNET */
#define XPAR_EMACLITE_0_DEVICE_ID XPAR_AXI_ETHERNET_DEVICE_ID
#define XPAR_EMACLITE_0_BASEADDR 0x40E00000
#define XPAR_EMACLITE_0_HIGHADDR 0x40E01FFF
#define XPAR_EMACLITE_0_TX_PING_PONG 1
#define XPAR_EMACLITE_0_RX_PING_PONG 1
#define XPAR_EMACLITE_0_INCLUDE_MDIO 1
#define XPAR_EMACLITE_0_INCLUDE_INTERNAL_LOOPBACK 0


/******************************************************************/


/* Definitions for peripheral AXI_LINEAR_FLASH */
#define XPAR_AXI_LINEAR_FLASH_NUM_BANKS_MEM 1


/******************************************************************/

/* Definitions for peripheral AXI_LINEAR_FLASH */
#define XPAR_AXI_LINEAR_FLASH_S_AXI_MEM0_BASEADDR 0x60000000

/******************************************************************/

/* Canonical definitions for peripheral AXI_LINEAR_FLASH */
#define XPAR_EMC_0_NUM_BANKS_MEM 1
#define XPAR_EMC_0_S_AXI_MEM0_BASEADDR 0x60000000
#define XPAR_EMC_0_S_AXI_MEM0_HIGHADDR 0x61FFFFFF

#define XPAR_AXI_EMC

/******************************************************************/


/* Definitions for peripheral AXI_AD9144_CORE */
#define XPAR_AXI_AD9144_CORE_BASEADDR 0x44A00000
#define XPAR_AXI_AD9144_CORE_HIGHADDR 0x44A0FFFF


/* Definitions for peripheral AXI_AD9144_DMA */
#define XPAR_AXI_AD9144_DMA_BASEADDR 0x7C420000
#define XPAR_AXI_AD9144_DMA_HIGHADDR 0x7C420FFF


/* Definitions for peripheral AXI_AD9144_JESD_TX_AXI */
#define XPAR_AXI_AD9144_JESD_TX_AXI_BASEADDR 0x44A90000
#define XPAR_AXI_AD9144_JESD_TX_AXI_HIGHADDR 0x44A93FFF


/* Definitions for peripheral AXI_AD9144_XCVR */
#define XPAR_AXI_AD9144_XCVR_BASEADDR 0x44A60000
#define XPAR_AXI_AD9144_XCVR_HIGHADDR 0x44A6FFFF


/* Definitions for peripheral AXI_AD9680_CORE */
#define XPAR_AXI_AD9680_CORE_BASEADDR 0x44A10000
#define XPAR_AXI_AD9680_CORE_HIGHADDR 0x44A1FFFF


/* Definitions for peripheral AXI_AD9680_DMA */
#define XPAR_AXI_AD9680_DMA_BASEADDR 0x7C400000
#define XPAR_AXI_AD9680_DMA_HIGHADDR 0x7C400FFF


/* Definitions for peripheral AXI_AD9680_JESD_RX_AXI */
#define XPAR_AXI_AD9680_JESD_RX_AXI_BASEADDR 0x44AA0000
#define XPAR_AXI_AD9680_JESD_RX_AXI_HIGHADDR 0x44AA3FFF


/* Definitions for peripheral AXI_AD9680_XCVR */
#define XPAR_AXI_AD9680_XCVR_BASEADDR 0x44A50000
#define XPAR_AXI_AD9680_XCVR_HIGHADDR 0x44A5FFFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral AXI_GPIO */
#define XPAR_AXI_GPIO_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_HIGHADDR 0x40000FFF
#define XPAR_AXI_GPIO_DEVICE_ID 0
#define XPAR_AXI_GPIO_INTERRUPT_PRESENT 1
#define XPAR_AXI_GPIO_IS_DUAL 1


/* Definitions for peripheral AXI_GPIO_LCD */
#define XPAR_AXI_GPIO_LCD_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_LCD_HIGHADDR 0x40010FFF
#define XPAR_AXI_GPIO_LCD_DEVICE_ID 1
#define XPAR_AXI_GPIO_LCD_INTERRUPT_PRESENT 1
#define XPAR_AXI_GPIO_LCD_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_GPIO */
#define XPAR_GPIO_0_BASEADDR 0x40000000
#define XPAR_GPIO_0_HIGHADDR 0x40000FFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_GPIO_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 1
#define XPAR_GPIO_0_IS_DUAL 1

/* Canonical definitions for peripheral AXI_GPIO_LCD */
#define XPAR_GPIO_1_BASEADDR 0x40010000
#define XPAR_GPIO_1_HIGHADDR 0x40010FFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_AXI_GPIO_LCD_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 1
#define XPAR_GPIO_1_IS_DUAL 0


/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_IIC_MAIN */
#define XPAR_AXI_IIC_MAIN_DEVICE_ID 0
#define XPAR_AXI_IIC_MAIN_BASEADDR 0x41600000
#define XPAR_AXI_IIC_MAIN_HIGHADDR 0x41600FFF
#define XPAR_AXI_IIC_MAIN_TEN_BIT_ADR 0
#define XPAR_AXI_IIC_MAIN_GPO_WIDTH 1


/******************************************************************/

/* Canonical definitions for peripheral AXI_IIC_MAIN */
#define XPAR_IIC_0_DEVICE_ID XPAR_AXI_IIC_MAIN_DEVICE_ID
#define XPAR_IIC_0_BASEADDR 0x41600000
#define XPAR_IIC_0_HIGHADDR 0x41600FFF
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 1


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 16
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_INTC */
#define XPAR_AXI_INTC_DEVICE_ID 0
#define XPAR_AXI_INTC_BASEADDR 0x41200000
#define XPAR_AXI_INTC_HIGHADDR 0x41200FFF
#define XPAR_AXI_INTC_KIND_OF_INTR 0xFFFF05DE
#define XPAR_AXI_INTC_HAS_FAST 0
#define XPAR_AXI_INTC_IVAR_RESET_VALUE 0x0000000000000010
#define XPAR_AXI_INTC_NUM_INTR_INPUTS 16
#define XPAR_AXI_INTC_ADDR_WIDTH 32


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x41200FFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_AXI_INTC_DEVICE_ID
#define XPAR_AXI_INTC_TYPE 0U
#define XPAR_AXI_TIMER_INTERRUPT_MASK 0X000001U
#define XPAR_AXI_INTC_AXI_TIMER_INTERRUPT_INTR 0U
#define XPAR_AXI_ETHERNET_IP2INTC_IRPT_MASK 0X000002U
#define XPAR_AXI_INTC_AXI_ETHERNET_IP2INTC_IRPT_INTR 1U
#define XPAR_AXI_UART_INTERRUPT_MASK 0X000010U
#define XPAR_AXI_INTC_AXI_UART_INTERRUPT_INTR 4U
#define XPAR_AXI_GPIO_LCD_IP2INTC_IRPT_MASK 0X000020U
#define XPAR_AXI_INTC_AXI_GPIO_LCD_IP2INTC_IRPT_INTR 5U
#define XPAR_AXI_IIC_MAIN_IIC2INTC_IRPT_MASK 0X000200U
#define XPAR_AXI_INTC_AXI_IIC_MAIN_IIC2INTC_IRPT_INTR 9U
#define XPAR_AXI_SPI_IP2INTC_IRPT_MASK 0X000400U
#define XPAR_AXI_INTC_AXI_SPI_IP2INTC_IRPT_INTR 10U
#define XPAR_AXI_GPIO_IP2INTC_IRPT_MASK 0X000800U
#define XPAR_AXI_INTC_AXI_GPIO_IP2INTC_IRPT_INTR 11U
#define XPAR_AXI_AD9680_DMA_IRQ_MASK 0X001000U
#define XPAR_AXI_INTC_AXI_AD9680_DMA_IRQ_INTR 12U
#define XPAR_AXI_AD9144_DMA_IRQ_MASK 0X002000U
#define XPAR_AXI_INTC_AXI_AD9144_DMA_IRQ_INTR 13U
#define XPAR_AXI_AD9680_JESD_RX_AXI_IRQ_MASK 0X004000U
#define XPAR_AXI_INTC_AXI_AD9680_JESD_RX_AXI_IRQ_INTR 14U
#define XPAR_AXI_AD9144_JESD_TX_AXI_IRQ_MASK 0X008000U
#define XPAR_AXI_INTC_AXI_AD9144_JESD_TX_AXI_IRQ_INTR 15U

/******************************************************************/

/* Canonical definitions for peripheral AXI_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_AXI_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000U
#define XPAR_INTC_0_HIGHADDR 0x41200FFFU
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFF05DEU
#define XPAR_INTC_0_HAS_FAST 0U
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x0000000000000010U
#define XPAR_INTC_0_NUM_INTR_INPUTS 16U
#define XPAR_INTC_0_ADDR_WIDTH 32U
#define XPAR_INTC_0_INTC_TYPE 0U

#define XPAR_INTC_0_TMRCTR_0_VEC_ID XPAR_AXI_INTC_AXI_TIMER_INTERRUPT_INTR
#define XPAR_INTC_0_EMACLITE_0_VEC_ID XPAR_AXI_INTC_AXI_ETHERNET_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_UARTLITE_0_VEC_ID XPAR_AXI_INTC_AXI_UART_INTERRUPT_INTR
#define XPAR_INTC_0_GPIO_1_VEC_ID XPAR_AXI_INTC_AXI_GPIO_LCD_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_IIC_0_VEC_ID XPAR_AXI_INTC_AXI_IIC_MAIN_IIC2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_0_VEC_ID XPAR_AXI_INTC_AXI_SPI_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_GPIO_0_VEC_ID XPAR_AXI_INTC_AXI_GPIO_IP2INTC_IRPT_INTR

/******************************************************************/

/* Definitions for driver MIG_7SERIES */
#define XPAR_XMIG7SERIES_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_DDR_CNTRL */
#define XPAR_AXI_DDR_CNTRL_DEVICE_ID 0U
#define XPAR_AXI_DDR_CNTRL_DDR3_ROW_WIDTH 14U
#define XPAR_AXI_DDR_CNTRL_DDR3_COL_WIDTH 0U
#define XPAR_AXI_DDR_CNTRL_DDR3_BANK_WIDTH 3U
#define XPAR_AXI_DDR_CNTRL_DDR3_DQ_WIDTH 64U


/******************************************************************/


/* Definitions for peripheral AXI_DDR_CNTRL */
#define XPAR_AXI_DDR_CNTRL_BASEADDR 0x80000000
#define XPAR_AXI_DDR_CNTRL_HIGHADDR 0xFFFFFFFF


/******************************************************************/

/* Canonical definitions for peripheral AXI_DDR_CNTRL */
#define XPAR_MIG7SERIES_0_DEVICE_ID XPAR_AXI_DDR_CNTRL_DEVICE_ID
#define XPAR_MIG7SERIES_0_DDR_ROW_WIDTH 14U
#define XPAR_MIG7SERIES_0_DDR_COL_WIDTH 0U
#define XPAR_MIG7SERIES_0_DDR_BANK_WIDTH 3U
#define XPAR_MIG7SERIES_0_DDR_DQ_WIDTH 64U
#define XPAR_MIG7SERIES_0_BASEADDR 0x80000000U
#define XPAR_MIG7SERIES_0_HIGHADDR 0xFFFFFFFFU


/******************************************************************/

/* Definitions for driver SPI */
#define XPAR_XSPI_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_SPI */
#define XPAR_AXI_SPI_DEVICE_ID 0U
#define XPAR_AXI_SPI_BASEADDR 0x44A70000U
#define XPAR_AXI_SPI_HIGHADDR 0x44A70FFFU
#define XPAR_AXI_SPI_FIFO_DEPTH 16U
#define XPAR_AXI_SPI_FIFO_EXIST 1U
#define XPAR_AXI_SPI_SPI_SLAVE_ONLY 0U
#define XPAR_AXI_SPI_NUM_SS_BITS 8U
#define XPAR_AXI_SPI_NUM_TRANSFER_BITS 8U
#define XPAR_AXI_SPI_SPI_MODE 0U
#define XPAR_AXI_SPI_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_AXI_SPI_AXI4_BASEADDR 0U
#define XPAR_AXI_SPI_AXI4_HIGHADDR 0U
#define XPAR_AXI_SPI_XIP_MODE 0U

/* Canonical definitions for peripheral AXI_SPI */
#define XPAR_SPI_0_DEVICE_ID 0U
#define XPAR_SPI_0_BASEADDR 0x44A70000U
#define XPAR_SPI_0_HIGHADDR 0x44A70FFFU
#define XPAR_SPI_0_FIFO_DEPTH 16U
#define XPAR_SPI_0_FIFO_EXIST 1U
#define XPAR_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_0_NUM_SS_BITS 8U
#define XPAR_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_0_SPI_MODE 0U
#define XPAR_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_SPI_0_AXI4_BASEADDR 0U
#define XPAR_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_SPI_0_XIP_MODE 0U
#define XPAR_SPI_0_USE_STARTUP 0U



/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_TIMER */
#define XPAR_AXI_TIMER_DEVICE_ID 0U
#define XPAR_AXI_TIMER_BASEADDR 0x41C00000U
#define XPAR_AXI_TIMER_HIGHADDR 0x41C00FFFU
#define XPAR_AXI_TIMER_CLOCK_FREQ_HZ 100000000U


/******************************************************************/

/* Canonical definitions for peripheral AXI_TIMER */
#define XPAR_TMRCTR_0_DEVICE_ID 0U
#define XPAR_TMRCTR_0_BASEADDR 0x41C00000U
#define XPAR_TMRCTR_0_HIGHADDR 0x41C00FFFU
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_AXI_TIMER_CLOCK_FREQ_HZ

/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 2

/* Definitions for peripheral AXI_UART */
#define XPAR_AXI_UART_BASEADDR 0x40600000
#define XPAR_AXI_UART_HIGHADDR 0x40600FFF
#define XPAR_AXI_UART_DEVICE_ID 0
#define XPAR_AXI_UART_BAUDRATE 115200
#define XPAR_AXI_UART_USE_PARITY 0
#define XPAR_AXI_UART_ODD_PARITY 0
#define XPAR_AXI_UART_DATA_BITS 8


/* Definitions for peripheral SYS_MB_DEBUG */
#define XPAR_SYS_MB_DEBUG_BASEADDR 0x41400000
#define XPAR_SYS_MB_DEBUG_HIGHADDR 0x41400FFF
#define XPAR_SYS_MB_DEBUG_DEVICE_ID 1
#define XPAR_SYS_MB_DEBUG_BAUDRATE 0
#define XPAR_SYS_MB_DEBUG_USE_PARITY 0
#define XPAR_SYS_MB_DEBUG_ODD_PARITY 0
#define XPAR_SYS_MB_DEBUG_DATA_BITS 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_UART */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_AXI_UART_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_UARTLITE_0_HIGHADDR 0x40600FFF
#define XPAR_UARTLITE_0_BAUDRATE 115200
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 8

/* Canonical definitions for peripheral SYS_MB_DEBUG */
#define XPAR_UARTLITE_1_DEVICE_ID XPAR_SYS_MB_DEBUG_DEVICE_ID
#define XPAR_UARTLITE_1_BASEADDR 0x41400000
#define XPAR_UARTLITE_1_HIGHADDR 0x41400FFF
#define XPAR_UARTLITE_1_BAUDRATE 0
#define XPAR_UARTLITE_1_USE_PARITY 0
#define XPAR_UARTLITE_1_ODD_PARITY 0
#define XPAR_UARTLITE_1_DATA_BITS 0


/******************************************************************/

#endif  /* end of protection macro */
